import type { Metadata } from "next"
import { Work_Sans } from "next/font/google"
import { twMerge } from "tailwind-merge"

import { ThemeProvider } from "@/components/theme-provider"

import "@/styles/globals.css"

import { Footer } from "@/components/custom/footer"
import { Header } from "@/components/custom/header"
import { cn } from "@/lib/utils"

const WorkSans = Work_Sans({ subsets: ["latin"], variable: "--font-work-sans" })

export const metadata: Metadata = {
  title: "ILH · Aide aux codes",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={cn(
          "flex min-h-screen flex-col justify-between bg-background font-sans antialiased",
          WorkSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="max-w-8xl mx-auto mt-8 w-full flex-grow">
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
